# Generated by Django 3.0.8 on 2020-08-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name_plural': 'Trips'},
        ),
    ]
