# Generated by Django 3.0.8 on 2020-08-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200728_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='has_sizes',
            new_name='has_people',
        ),
    ]
