# Generated by Django 3.0.8 on 2020-08-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Bookings'),
        ),
    ]
